### ISSUE TITLE
Hi ,Cool boy! i miss  a quesion .can you help me ?

### ISSUE THREAD

**Issue by bestbelief** [sparten11740/angular-protobuf-example#1]

**Comment by bestbelief** [comment]
i want know what need to add in schemas_pb.js? need to edit in schemas_pb.js?

**Comment by sparten11740** [comment]
The file schemas_pb.js is automatically produced by the protoc compiler. You have to define your protobuf models (usually in a file suffixed with .proto, to be found in `/src/proto/schemas.proto`) and feed this file into the protoc compiler. In my case this command did the job: `protoc --proto_path=src\proto\ --js_out=import_style=commonjs,binary:src\assets\js src\proto\schemas.proto`

I strongly advise against editing this file manually. If you run the protoc compiler again (i.e. if you add new schemas), your changes will be overwritten.

**Comment by bestbelief** [comment]
i will try again ! thank you very much!
