### ISSUE TITLE
Can't resolve 'google-protobuf' 

### ISSUE THREAD

**Issue by experionakash** [sparten11740/angular-protobuf-example#2]
Hi,

I have cloned your repo and tried to run it but I'm getting the following error.
Can you pls help me out?

> ERROR in ./src/assets/js/schemas_pb.js
> Module not found: Error: Can't resolve 'google-protobuf' in 'E:\Training\protbuff\angular-protobuf-example-master\src\assets\js'
>  @ ./src/assets/js/schemas_pb.js 7:11-37
>  @ ./src/app/core/protobuf.service.ts
>  @ ./src/app/core/core.module.ts
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by sparten11740** [comment]
Hey, sorry for the late reply. Have you tried issuing the command `npm install google-protobuf --save` in your project dir?

**Comment by sparten11740** [comment]
I added the missing npm dependency, the project can now be built & started as described in the `Run the project` section of the readme.
